steps:
  - name: node:16.0.0
    entrypoint: npm
    args: ['install']
  - name: node:16.0.0
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '-v', '20220628t175507']
timeout: '1600s'
